// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://goeiyfrihltnxloqwrog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvZWl5ZnJpaGx0bnhsb3F3cm9nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMjI5NTcsImV4cCI6MjA2ODU5ODk1N30.dnl54Ph9tz119x1UwXbolhRIapU-hCb22CnxyroC8Xs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});